name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: pkwagner/yasdi2mqtt
      DOCKER_PLATFORMS: linux/amd64,linux/arm64
      SMOKE_TIMEOUT: 120
      SMOKE_PORT: 8080
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: QEMU setup
        if: success()
        uses: docker/setup-qemu-action@v1
      - name: Docker Buildx setup
        if: success()
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Enable Docker experimental features
        if: success()
        run: |
          echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Build
        if: success()
        run: |
          TAGS="-t ${DOCKER_IMAGE}:latest"
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            TAGS="$TAGS -t ${DOCKER_IMAGE}:stable"
            TAGS="$TAGS -t ${DOCKER_IMAGE}:${GITHUB_REF#refs/tags/v}"
          fi
        
          for PLATFORM in ${DOCKER_PLATFORMS//,/ }; do
            docker build \
              --platform $PLATFORM \
              --load \
              $TAGS \
              .
          done
      - name: Fire up containers for smoke testing
        if: success()
        run: |
          for PLATFORM in ${DOCKER_PLATFORMS//,/ }; do
            docker run --rm -d --name ${PLATFORM////-} --network=host --env-file .github/workflows/smoke-testing.env --platform $PLATFORM -e MQTT_PORT=$SMOKE_PORT -e MQTT_USER=$PLATFORM ${DOCKER_IMAGE}:latest
            docker ps
          done
      - name: Set up smoke testing workbench
        if: success()
        uses: pkwagner/smoky-mqtt@v0.9
        with:
          ids: ${{env.DOCKER_PLATFORMS}}
          timeout: ${{env.SMOKE_TIMEOUT}}
          port: ${{env.SMOKE_PORT}}
      - name: TMP
        if: always()
        run: |
          docker run --rm --network=host --env-file .github/workflows/smoke-testing.env --platform linux/arm64 -e MQTT_PORT=$SMOKE_PORT -e MQTT_USER=gogo ${DOCKER_IMAGE}:latest
          for i in {1..10}; do
            docker ps
            sleep 3
          done
