name: smoky-mqtt-test

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: pkwagner/yasdi2mqtt
      DOCKER_PLATFORMS: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: QEMU setup
        uses: docker/setup-qemu-action@v1
      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: MQTT smokefire setup
        uses: pkwagner/smoky-mqtt@v0.4
        with:
          ids: "test1,test2"
          timeout: 10
