name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: pkwagner/yasdi2mqtt
      DOCKER_PLATFORMS: linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: QEMU setup
        uses: docker/setup-qemu-action@v1
      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Build & Deploy
        if: success()
        run: |
          TAGS="--tag ${DOCKER_IMAGE}"
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            TAGS="$TAGS --tag ${DOCKER_IMAGE}:stable"
            TAGS="$TAGS --tag ${DOCKER_IMAGE}:${GITHUB_REF#refs/tags/v}"
          fi

          docker build \
            --platform $DOCKER_PLATFORMS \
            $TAGS \
            .
      - name: Smokefire testing
        if: success()
        run: |
          echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
          
          for PLATFORM in ${DOCKER_PLATFORMS//,/ }; do
            docker run --rm -d --name ${PLATFORM////} --network=host --platform $PLATFORM -e YASDI_CONFIG=... -e YASDI_DRIVER_ID=1 -e YASDI_MAX_DEVICE_COUNT=1 -e YASDI_UPDATE_INTERVAL=1 -e MQTT_TOPIC_PREFIX=... -e MQTT_SERVER=localhost -e MQTT_PORT=8080 -e MQTT_USER=$PLATFORM -e MQTT_PASSWORD=nopass $DOCKER_IMAGE
          done
      - name: MQTT smokefire setup
        uses: pkwagner/smoky-mqtt@v0.5
        with:
          ids: ${{env.DOCKER_PLATFORMS}}
          timeout: 60
